#!/bin/bash

# Function to display script usage/help information
function display_usage() {
  echo "Usage: ./my_script.sh -f <filename> -o <output_dir> -t <type>"
  echo "Options:
  -f <filename>: Specify the input filename.
  -o <output_dir>: Specify the output directory where the results will be stored.
  -t <type>: Specify the type of action to perform. Supported types are 'process' and 'analyze'.
  -h: Display this help information."
}


# Check if no arguments are provided.
# If so, display usage information and exit


if [ $# -eq 0 ]; then
    display_usage
    exit 1
fi

# Initialize variables
filename=""
output_dir=""
action=""

# Process command-line options and arguments
while getopts ":f:o:t:h" opt; do
    case $opt in
        f)
            # option f
            filename="$OPTARG"
            ;;
        o)
           # option o
            output_dir="$OPTARG"
            ;;
        t)
          # option t
            action="$OPTARG"
            ;;
        h)
           # option h
            # display usage and exit
            display_usage
            exit 0
            ;;
        \?)
            # any other option
            echo "Invalid option: -$OPTARG"
             # display usage and exit
            display_usage
            exit 1
            ;;
    esac
done

# Check if all required switches are provided
 if [[ ! "$filename" || ! "$output_dir" || ! "$action" ]]; then
    echo "Error: Missing required options."
    # display usage and exit
    display_usage
    exit 1
fi
   

# Check if the -t switch has a valid argument
if [[ "$action" != "process" && "$action" != "analyze" ]]; then
    echo "Error: Invalid action type. Supported types are 'process' and 'analyze'."
     # exit
    exit 1
fi
   

# Check if the specified input filename exists and is a regular file
if [ ! -f "$filename" ]; then
    echo "Error: Input file '$filename' does not exist or is not a regular file."
     # exit
    exit 1
fi
   

# Check if the specified output directory exists and is a directory
if [ ! -d "$output_dir" ]; then
    echo "Error: Output directory '$output_dir' does not exist."
    # exit
    exit 1
fi
   

# Perform the selected action based on the user input
# if action is process
    if [ "$action" = "process" ]; then
    echo "Processing task will be performed on '$filename' and the results will be stored in '$output_dir'."
# else if action is analyze
    elif [ "$action" = "analyze" ]; then
    echo "Analysis will be performed on '$filename' and t
