#!/bin/bash

# Prompt the user to enter a file name/path

file= echo "Enter a file name/path: "
read file
read -p "Enter a file name/path: " file

# Check if the file exists

if [ -f $file ]
then
echo "File exists"

  # If the file exists, print the following information:

    echo "File Information:"
    echo "-----------------"
    echo "File: $file"
   FILESIZE=$(stat -c%s "$file") echo "Size: $FILESIZE"
   perm=$(chmod go-rw  $file) echo "Permissions: $perm"
   create=$(stat -c '%w' $file) echo "Created: "
    mod=$(stat -c %y "$file") echo "Modified: $mod"

  # if the file doesn't exist, print an error message
  else
echo "Error: File '$file' does not exist."
fi
