#!/bin/bash

# Function to display script usage/help information
function display_usage() {
  echo "Usage: ./loganalyzer.sh -f <filename>"
  echo "Options:
  -f <filename>: Specify the log filename.
  -h: Display this help information."
}

# Initialize variables
filename=""
alerts='[Ee]rror|[Ww]arning'


while getopts ":f:h" opt; do
  case $opt in
    f)
      filename="$OPTARG"
      ;;
    h)
      display_usage
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      display_usage
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      display_usage
      exit 1
      ;;
  esac
done

# Check if filename was input
if [ -z "$filename" ]; then
  echo "Error: Please provide a filename."
  display_usage
  exit 1
fi

# Check if the file exists in system
if [ ! -f "$filename" ]; then
  echo "File '$filename' does not exist. "
  display_usage
  exit 1
fi

# If file exists, print information
echo "File Information:"
FILESIZE=$(stat -c%s "$filename") 
echo "Size: $FILESIZE"
perm=$(chmod go-rw  "$filename") 
echo "Permissions: $perm"
mod=$(stat -c %y "$filename") 
echo "Modified: $mod"

# Analyze log file
echo "Log Analysis Results:"
count=$(awk -v pattern="$alerts" '$0 ~ pattern' "$filename" | grep -vE '^[[:space:]]*$' | sort | uniq -c | sort -nr)
echo "$count"

